#!/bin/bash

function usage(){
    cat << EOF
Usage: dispatched-import [-p] -f fifo-dir -g git-dir -i input-file
EOF
}

while getopts "pg:f:i:" opt
do
    case $opt in
        p)
            PIPES=-p
        ;;

        g)
            GIT_DIR=$OPTARG
        ;;

        f)
            FIFO_DIR=$OPTARG
        ;;

        i)
            INPUT_FILE=$OPTARG
        ;;

        \?)
            usage >&2
            exit 1
        ;;
    esac
done

set -ex

mkdir -p $FIFO_DIR

../BD-lev/levitation $PIPES -o $FIFO_DIR/%c.fi $INPUT_FILE &

mkdir -p $GIT_DIR
cd $GIT_DIR
git init --bare base.git
pushd base.git
git fast-import --date-format=rfc2822 < $FIFO_DIR/m.fi
popd

for SUB in A B C D E F G H I J K L M N O P Q R S T U V W X Y Z _
do
    git clone --bare base.git $SUB.git
    (cd $SUB.git && git fast-import --date-format=rfc2822 < $FIFO_DIR/$SUB.fi) &
done

wait
